const menu_data = [
  // {
  //   id: 1,
  //   mega_menu: false,
  //   has_dropdown: true,
  //   title: "Home",
  //   link: "/",
  //   active: "active",
  //   sub_menus: [
  //     { link: "/", title: "Data analytics" },
  //     { link: "/home-2", title: "Payment Gateway" },
  //     { link: "/home-3", title: "CRM Software" },
  //     { link: "/home-4", title: "Security Software" },
  //     { link: "/home-5", title: "Saas" },
  //   ],
  // },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "About Us",
    link: "/about",
    active: "",
    // sub_menus: [
    //   { link: "/about", title: "Company" },
    //   { link: "/#", title: "Career" },
    //   { link: "/#", title: "Testimonials" },
    // ],
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "Surveillance Soutions",
    link: "/surveillance",
    active: "",
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "Cyber Security Solutions",
    link: "/cyber-security",
    active: "",
  },
  // {
  //   id: 2,
  //   mega_menu: false,
  //   has_dropdown: false,
  //   title: "Surveillance",
  //   link: "/#",
  //   active: "",
  // },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "SaaP",
    link: "/service#spd",
    active: "",
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "SaaS",
    link: "/service#saas",
    active: "",
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "e-Governance Solutions",
    link: "/e-governance-solutions",
    active: "",
  },

  // {
  //   id: 3,
  //   mega_menu: false,
  //   has_dropdown: true,
  //   title: "Services +",
  //   link: "/services",
  //   active: "",
  //   sub_menus: [
  //     { link: "/services", title: "Software Product Development" },
  //     { link: "/services", title: "Software as a Service (SaaS)" },
  //     { link: "/services", title: "Web Development" },
  //     { link: "/services", title: "E-Commerce Development" },
  //     { link: "/services", title: "Digital Transformation Services" },
  //   ],
  // },

  // {
  //   id: 5,
  //   mega_menu: false,
  //   has_dropdown: false,
  //   title: "Contact",
  //   link: "/contact",
  //   active: "",
  // },
];
export default menu_data;
