const menu_data = [
  // {
  //   id: 1,
  //   mega_menu: false,
  //   has_dropdown: true,
  //   title: "Home",
  //   link: "/",
  //   active: "active",
  //   sub_menus: [
  //     { link: "/", title: "Data analytics" },
  //     { link: "/home-2", title: "Payment Gateway" },
  //     { link: "/home-3", title: "CRM Software" },
  //     { link: "/home-4", title: "Security Software" },
  //     { link: "/home-5", title: "Saas" },
  //   ],
  // },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: true,
    title: "About Us +",
    link: "/about",
    active: "",
    sub_menus: [
      { link: "/about", title: "About Us" },
      { link: "/team", title: "Team" },
      // { link: "/#", title: "Career" },
      // { link: "/#", title: "Testimonials" },
    ],
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "Surveillance Soutions",
    link: "/surveillance",
    active: "",
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "Cyber Security Solutions",
    link: "/cyber-security",
    active: "",
  },
  // {
  //   id: 2,
  //   mega_menu: false,
  //   has_dropdown: false,
  //   title: "Surveillance",
  //   link: "/#",
  //   active: "",
  // },
  {
    id: 2,
    mega_menu: true,
    has_dropdown: true,
    title: "Products +",
    link: "/software-as-a-product",
    active: "",
    sub_menus: [
      { link: "/workfusion", title: "Workfusion" },
      {
        link: "/document-management-system",
        title: "Document Management System",
      },
      // { link: "/service", title: "Development" },
    ],
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "Services",
    link: "/service",
    active: "",
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: true,
    title: "e-Governance Solutions +",
    link: "/e-governance-solutions",
    active: "",
    sub_menus: [
      { link: "/digital-mapping", title: "Digital Mapping" },
      // { link: "/geo-referencing", title: "Geo-referencing" },
      { link: "/kumbh2025", title: "Kumbh 2025" },
    ],
  },

  // {
  //   id: 3,
  //   mega_menu: false,
  //   has_dropdown: true,
  //   title: "Services +",
  //   link: "/services",
  //   active: "",
  //   sub_menus: [
  //     { link: "/services", title: "Software Product Development" },
  //     { link: "/services", title: "Software as a Service (SaaS)" },
  //     { link: "/services", title: "Web Development" },
  //     { link: "/services", title: "E-Commerce Development" },
  //     { link: "/services", title: "Digital Transformation Services" },
  //   ],
  // },

  // {
  //   id: 5,
  //   mega_menu: false,
  //   has_dropdown: false,
  //   title: "Contact",
  //   link: "/contact",
  //   active: "",
  // },
];
export default menu_data;
